version: "3"
services:

  db:
    container_name: db_movies
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apinode

  web:
    container_name: api_movies
    build: .
    ports:
      - 3001:3001
    depends_on:
      - db
    links:
      - db:database
    environment:
      - DB_HOST=db